apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-dist-builder
spec:
  selector:
    app: api-dist-builder
  ports:
    - protocol: TCP
      port: 7200
      targetPort: 7200